### ISSUE TITLE
Game crahses after stats are in DB

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kr4uzi/gamespy-emulator#4]
```
Ok, So the emulator works great... sorta. I Use this login server with 
bf2statistics. After i have played 1 game, the game crashed. If i delete my 
stats from the database, all the sudden i can log in again. So there is an 
error retrieving stats for some reason


```

Original issue reported on code.google.com by `wilson.steven10@gmail.com` on 27 Nov 2010 at 2:34

**Comment by kr4uzi** [comment]
couldn't reproduce this bug in my the latest test, additionally i've added a injector in this project which makes the whole hosts editing obsolete.
